### ISSUE TITLE
[TODO] ver2.0.1 ideas

### ISSUE THREAD

**Issue by YunKi-H** [ittzggd/24HoursAreNotEnough#142]
### ISSUE
 * Type: `Ideas`
 ### ⚽ GOAL⚽ : 개선사항
 ### 🦄TODO🦄 
- [ ] Calendar 이번달 새로고침할때만 로딩(api call)하는 로직은 어떤지?
- [ ] Coredata 수정 (Table 재구성)
- [ ] 에러 케이스 세분화 처리
- [ ] 로깅용 지표 정량적 수치화
- [ ] 또팩토링....
- [ ] 개발과정 이슈정리
- [ ] 위젯
- [ ] 시계는 와치...
- [ ] Live Activities (dynamic island)
- [ ] 공?지 -> 
- [ ] iPhone 13 mini 하단바와 홈바 너무 가까움
