### ISSUE TITLE
[TODO] V3

### ISSUE THREAD

**Issue by ittzggd** [ittzggd/24HoursAreNotEnough#148]
**기존 리팩토링**
- [x] SwiftLint 적용
- [x] coreData 제거
- [ ] 테스트 코드 추가
- [x] 주간 & 월간 그래프 반올림 -> 반내림 
- [x] Main에 적용 안 된 TabView 등 오류 수정
- [ ] Const String 들 따로 빼서 관리
- [x] 다크모드용 Color Asset 적용
- [x] CalendarGrid 내부 구조 개편 [Int] -> [Date]

**새로 추가되는 기능**
- [x] 총 출입시간중 인정 출입시간

- [ ] README.md 프로젝트 수행기간 기입

**Comment by YunKi-H** [comment]
상수값들은 enum으로 빼는게 나을까요?
